package gui;

import entities.Cliente;
import implement.ImplCliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ClientGUI extends javax.swing.JPanel {
    DefaultTableModel modelo1;
    ImplCliente ic = new ImplCliente();

    public ClientGUI() {
        initComponents();
        ReporteDataCT();
        
        jButtonActualizar.setVisible(true);
        jButtonLimpiar.setVisible(true);
        jTextField_id.setVisible(true);
        jPanelFormulario.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFormulario = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_Dni_ruc = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel_direccion = new javax.swing.JLabel();
        jLabel_origen = new javax.swing.JLabel();
        jTextField_Dni_ruc = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_direccion = new javax.swing.JTextField();
        jButton_grabar = new javax.swing.JButton();
        jTextField_origen = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextField_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();

        jPanelFormulario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelFormularioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_titulo.setText("Formulario Cliente");
        jLabel_titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel_Dni_ruc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Dni_ruc.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_Dni_ruc.setText("Dni/Ruc:");
        jLabel_Dni_ruc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel_Dni_rucAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_Nombre.setText("Nombre:");

        jLabel_telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_telefono.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_telefono.setText("Telefono:");

        jLabel_direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_direccion.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_direccion.setText("Direccion:");

        jLabel_origen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_origen.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_origen.setText("Origen:");
        jLabel_origen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton_grabar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_grabar.setForeground(new java.awt.Color(0, 102, 153));
        jButton_grabar.setText("Grabar");
        jButton_grabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_grabarMouseClicked(evt);
            }
        });
        jButton_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_grabarActionPerformed(evt);
            }
        });

        jTextField_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_origenActionPerformed(evt);
            }
        });

        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/actualizar (1).png"))); // NOI18N
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Limpieza.png"))); // NOI18N
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/eliminar (1).png"))); // NOI18N
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jTableCliente.setBackground(new java.awt.Color(0, 102, 153));
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Dni/Ruc", "Nombre", "Telefono", "Direccion", "Origen"
            }
        ));
        jTableCliente.setName(""); // NOI18N
        jTableCliente.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);
        jPanelFormulario.setLayout(jPanelFormularioLayout);
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Dni_ruc))
                            .addComponent(jLabel_telefono)
                            .addComponent(jLabel_direccion)
                            .addComponent(jLabel_origen)))
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Dni_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(558, 558, 558))))
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Dni_ruc)
                            .addComponent(jTextField_Dni_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_telefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_direccion)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_origen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 297, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void limpiarJTextField(){
        jTextField_id.setText("");
        jTextField_Dni_ruc.setText("");
        jTextField_Nombre.setText("");
        jTextField_telefono.setText("");
        jTextField_direccion.setText("");
        jTextField_origen.setText("");
        
    }
    public void AddOneReporteData(){
        Object[] fila = new Object[6];
        
        fila[0] = jTextField_id.getText();
        fila[1] = jTextField_Dni_ruc.getText();
        fila[2] = jTextField_Nombre.getText();
        fila[3] = jTextField_telefono.getText();
        fila[4] = jTextField_direccion.getText();
        fila[5] = jTextField_origen.getText();
        
        modelo1.addRow(fila);
        jTableCliente.setModel(modelo1);
                
    }
        public void updateOneReporteData(int rowSelected){
            //Object[] fila = new Object[6];
            jTableCliente.setValueAt(jTextField_id.getText(), rowSelected, 0);
            jTableCliente.setValueAt(jTextField_Dni_ruc.getText(), rowSelected, 1);
            jTableCliente.setValueAt(jTextField_Nombre.getText(), rowSelected, 2);
            jTableCliente.setValueAt(jTextField_telefono.getText(), rowSelected, 3);
            jTableCliente.setValueAt(jTextField_direccion.getText(), rowSelected, 4);
            jTableCliente.setValueAt(jTextField_origen.getText(), rowSelected, 5);  
    }
        

    public void ReporteDataCT(){
        System.out.print("tablaCliente");
        
        modelo1 = new DefaultTableModel();
        modelo1.addColumn("ID");
        modelo1.addColumn("Dni/Ruc");
        modelo1.addColumn("Nombre");
        modelo1.addColumn("Telefono");
        modelo1.addColumn("Direccion");
        modelo1.addColumn("Origen");
     
        for (Cliente pers : ic.reporteCliente()) {
            Object[] fila = new Object[6];
            fila[0] = pers.getCliente_id();
            fila[1] = pers.getCliente_dni_ruc();
            fila[2] = pers.getCliente_nombres();
            fila[3] = pers.getCliente_telefono();
            fila[4] = pers.getCliente_direccion();
            fila[5] = pers.getCliente_origen();

            modelo1.addRow(fila);
        }
        jTableCliente.setModel(modelo1);
    }
    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        int row=jTableCliente.getSelectedRow();

        System.out.print("tabla Cliente"+row);
        String id        = jTableCliente.getValueAt(row, 0).toString();
        String Dni_ruc   = jTableCliente.getValueAt(row, 1).toString();
        String nombres   = jTableCliente.getValueAt(row, 2).toString();
        String telefono  = jTableCliente.getValueAt(row, 3).toString();
        String direccion = jTableCliente.getValueAt(row, 4).toString();
        String origenn   = jTableCliente.getValueAt(row, 5).toString();

        jTextField_id.setText(id);
        jTextField_Dni_ruc.setText(Dni_ruc);
        jTextField_Nombre.setText(nombres);
        jTextField_telefono.setText(telefono);
        jTextField_direccion.setText(direccion);
        jTextField_origen.setText(origenn);
        jButton_grabar.setVisible(false);
        jButtonActualizar.setVisible(true);
        jButtonEliminar.setVisible(true);

    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jLabel_Dni_rucAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel_Dni_rucAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Dni_rucAncestorAdded

    private void jButton_grabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_grabarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_grabarMouseClicked

    private void jButton_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_grabarActionPerformed

        if(jTextField_Dni_ruc.getText().equals("")||
            jTextField_Nombre.getText().equals("")||
            jTextField_telefono.getText().equals("")||
            jTextField_direccion. getText().equals("")||
            jTextField_origen.getText().equals("")
        ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos completos");
        }else{

            Cliente c = new Cliente();
            c.setCliente_dni_ruc(jTextField_Dni_ruc.getText());
            c.setCliente_nombres(jTextField_Nombre.getText());
            c.setCliente_telefono(jTextField_telefono.getText());
            c.setCliente_direccion(jTextField_direccion.getText());
            c.setCliente_origen(jTextField_origen.getText());

            ic.registrarCliente(c);

            JOptionPane.showMessageDialog(null, "Se registro de manera satisfactoria");
            AddOneReporteData();
            limpiarJTextField();
        }
    }//GEN-LAST:event_jButton_grabarActionPerformed

    private void jTextField_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_origenActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
       

        if(jTextField_Dni_ruc.getText().equals("")||
            jTextField_Nombre.getText().equals("")||
            jTextField_telefono.getText().equals("")||
            jTextField_direccion.getText().equals("")||
            jTextField_origen.getText().equals("")
        ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos completos");

        }else{

            Cliente ct = new Cliente();
            ct.setCliente_dni_ruc(jTextField_Dni_ruc.getText());
            ct.setCliente_nombres(jTextField_Nombre.getText());
            ct.setCliente_telefono(jTextField_telefono.getText());
            ct.setCliente_direccion(jTextField_direccion.getText());
            ct.setCliente_origen(jTextField_origen.getText());
            

            ic.ActualizarCliente(ct);
            int row=jTableCliente.getSelectedRow();
            updateOneReporteData(row);
            JOptionPane.showMessageDialog(null, "Se actualizo de manera satisfactoria");
            limpiarJTextField();
            
            

        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiarJTextField();
        jButton_grabar.setVisible(true);
        jButtonActualizar.setVisible(false);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        System.out.print(jTextField_id.getText()+"sfdsfsdfsdf");
        ic.EliminarCliente(jTextField_id.getText());
        int row=jTableCliente.getSelectedRow();
        jTableCliente.removeAll();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jPanelFormularioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelFormularioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFormularioAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButton_grabar;
    private javax.swing.JLabel jLabel_Dni_ruc;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_origen;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextField_Dni_ruc;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_origen;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
